### ISSUE TITLE
Add continuous integration to `ryu-js` like `boa`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/ryu-js#3]

**Comment by HalidOdat** [comment]
Nevermind the the crate already has a `github/workflow`, so closing this.

**Comment by HalidOdat** [comment]
I'm reopening this because the CI is not complete, it does not have rustfmt, clippy, etc

**Comment by Razican** [comment]
We should also add some extra lints we use in Boa.

**Comment by HalidOdat** [comment]
> We should also add some extra lints we use in Boa.

That would be awesome!! :)

Also having some benchmarks would be nice too.

Edit: the crate has benchmarks but they are nightly bench ones I don't know how compatible it is with `critcmp` it is. since id does not use criterion <https://github.com/boa-dev/ryu-js/blob/master/benches/bench.rs>

**Comment by Razican** [comment]
> Also having some benchmarks would be nice too.
> 
> Edit: the crate has benchmarks but they are nightly bench ones I don't know how compatible it is with `critcmp` it is. since id does not use criterion <https://github.com/boa-dev/ryu-js/blob/master/benches/bench.rs>

I think we could start using criterion for this :)
